7 10 task cafe/kh/7 10 task
kostjkeee/UIKitDZ pull request #7
Opened 2024-02-14 09:08 UTC by kostjkeee

2024-02-14 09:40 UTC, kostjkeee commented
https://github.com/kostjkeee/UIKitDZ/assets/142137911/f4c7cca2-6fad-4eb3-9aec-86174c954bfe

2024-02-14 10:53 UTC, eugenegodzishevsky requested changes

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Controller/CoffeeRoastingViewController.swift
> +}
по гайдлайну надо добавить пустую строку в конце файла

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Controller/CoffeeViewController.swift
> +}
так же пустая строка

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Controller/IngredientsViewController.swift
> +}
тоже самое

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Extensions/UIViewController+Extension.swift
> +import UIKit
```suggestion
import UIKit
```
фаундэйшн можно убрать

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Controller/TotalBillViewController.swift
> +}
и здесь

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Extensions/UIViewController+Extension.swift
> +}
и вот здесь)

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Model/Coffee.swift
> +}
пустая строка

2024-02-14 10:53 UTC, eugenegodzishevsky commented on UIKitDZ/UIKitDZ/Model/TotalBillCalculator.swift
> +}
пустая строка

2024-02-14 11:01 UTC, Evgeny-Zverik commented on UIKitDZ/UIKitDZ/Model/TotalBillCalculator.swift
> +
```suggestion
```

2024-02-14 11:01 UTC, Evgeny-Zverik commented on UIKitDZ/UIKitDZ/Model/TotalBillCalculator.swift
> +
```suggestion
```

2024-02-15 05:03 UTC, eugenegodzishevsky commented
плюс

2024-02-18 12:12 UTC, merged